//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vinay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PostTable
    {
        public int PostId { get; set; }
        [DataType(DataType.MultilineText)]
        public string PostDescription { get; set; }
        public string PostImage { get; set; }
        public string PostImage1 { get; set; }
        public string PostImage2 { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.TimeSpan PostTime { get; set; }
        public string PostLat { get; set; }
        public string PostLng { get; set; }
        public string PostBy { get; set; }
        public int PostByRole { get; set; }
        public int Active { get; set; }
        public string PostVideo { get; set; }
    }
}
