//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vinay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_Master
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string PostedBy { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
